base_config: "base_sac_adroit_sample_efficient.yml"
env:
  env_id: "AdroitHandRelocateSparse-v1"
  max_episode_steps: 200
eval_env:
  max_episode_steps: 200

train:
  dataset_path: "demos/d4rl/AdroitHandRelocateSparse-v1/trajectory.h5"
